{ lib, ... }:
let
  inherit (lib) mkEnableOption mkOption types;

  easyeffectsAutoloadDevice = {
    options = {
      deviceName = mkOption {
        type = types.str;
        default = null;
        description = "Unique device name just used for filename";
      };
      deviceType = mkOption {
        type = types.enum [ "input" "output" ];
        default = null;
      };
      config = mkOption {
        type = types.str;
        default = null;
        description = "The json autoload config generated by easyeffects";
      };
    };
  };
in
{
  imports = lib.utils.scanPaths ./.;

  options.modules.services = {
    syncthing.enable = mkEnableOption "Syncthing";
    easyeffects = {
      enable = mkEnableOption "Easyeffects";
      autoloadDevices = mkOption {
        type = with types; listOf (submodule easyeffectsAutoloadDevice);
        default = [ ];
      };
    };
  };
}
