# To see the scripts generated by disko inspect the following derivations:

# WARN: The format script does not remove existing partitions on the disk. In
# most cases you'd want to run the destroy script before format.

# - config.system.build.diskoScript (runs destroy, format, mount)
# - config.system.build.formatScript
# - config.system.build.destroyScript
# - config.system.build.mountScript (useful for rescues)
{
  lib,
  cfg,
  pkgs,
  config,
  inputs,
  username,
  hostname,
}:
let
  inherit (lib)
    ns
    mkIf
    mkVMOverride
    nameValuePair
    filter
    elemAt
    unique
    splitString
    getExe
    mkBefore
    head
    getExe'
    mkForce
    listToAttrs
    singleton
    replaceStrings
    mkEnableOption
    mkOption
    types
    mapAttrsToList
    hasAttr
    any
    attrValues
    assertMsg
    stringToCharacters
    ;
  inherit (config.${ns}.hardware) raspberry-pi;
  inherit (config.${ns}.core) device;
in
[
  {
    guardType = "custom";
    enableOpt = false;

    opts = {
      tmpfsTmp = mkEnableOption "tmp on tmpfs";
      extendedLoaderTimeout = mkEnableOption ''
        an extended loader timeout of 30 seconds. Useful for switching to old
        generations on headless machines.
      '';

      zramFs = {
        enable = mkEnableOption ''
          creation of a zram-backed ext4 file system on boot. This is created
          earlier than the zram-generator so this file system can be used for /
          on impermanence systems. The ext4 parameters are also optimised for a
          RAM-backed use-case which is not natively possible with zram-generator.
        '';

        device = mkOption {
          type = types.str;
          readOnly = true;
          default =
            if config.zramSwap.enable then "/dev/zram${toString config.zramSwap.swapDevices}" else "/dev/zram0";
          description = ''
            Due to the zramSwap NixOS module reserving the first zram devices, we
            have to use the final device which will be
            /dev/zram${config.zramSwap.swapDevices}.
          '';
        };

        algorithm = mkOption {
          type = types.str;
          default = "zstd";
          description = "zram compression algorithm to use";
        };

        size = mkOption {
          type = types.str;
          default = null;
          description = ''
            Virtual size of the device and therefore the size of the ext4
            partition. Should be generous here to ensure there is enough
            headroom to make use of compression so roughly 3x memoryLimit is
            fine. Ideally memory limit is always hit before the device fills up.
          '';
        };

        memoryLimit = mkOption {
          type = types.str;
          default = null;
          example = "24G";
          description = ''
            Maximum amount of system memory the zram disk can use. This is
            final compressed size so is not correlated to the device's virtual
            capacity. Should probably be conservative here and keep this well
            under 50% system memory as this cannot be OOMED or evicted to swap
            like tmpfs can.
          '';
        };
      };

      type = mkOption {
        type = types.enum [
          "zfs"
          "ext4"
          "sd-image"
        ];
        default = null;
        description = "The type of filesystem on this host";
      };

      ext4.trim = removeAttrs (mkEnableOption "ext4 automatic trimming") [ "default" ];

      zfs = {
        trim = removeAttrs (mkEnableOption "ZFS automatic trimming") [ "default" ];

        encryption = {
          enable = mkOption {
            type = types.bool;
            readOnly = true;
            # Check for any pool datasets with encryption enable or child
            # datasets with encryption enabled
            default = any (v: v == true) (
              mapAttrsToList (
                _: pool:
                (hasAttr "encryption" pool.rootFsOptions)
                || (any (dataset: hasAttr "encryption" dataset.options) (attrValues pool.datasets))
              ) config.disko.devices.zpool
            );
            description = ''
              Whether the file system uses ZFS disk encryption. Derived from disko
              config.
            '';
          };

          passphraseCred = mkOption {
            type = with types; nullOr lines;
            default = null;
            description = ''
              Encrypted ZFS passphrase credential generated with
              `systemd-ask-password -n | systemd-creds encrypt --with-key=tpm2
              --name=zfs-passphrase -p - -`
            '';
          };
        };
      };

      swap =
        let
          inherit (config.${ns}.core.device) memory;
        in
        {
          file = {
            enable = mkEnableOption "swap file creation";
            size = mkOption {
              type = types.int;
              default =
                if memory <= 2 * 1024 then
                  memory * 2
                else if memory <= 8 * 1024 then
                  memory
                else
                  1024 * 4;
              description = "Size of swap file in megabytes";
            };
          };

          compression = mkOption {
            type = types.enum [
              "zram"
              "zswap"
            ];
            default = null;
            description = ''
              Swap optimisation method to use. Zwap should be preferred over zram
              swap but can only be used if the host has disk swap.

              https://chrisdown.name/2026/03/24/zswap-vs-zram-when-to-use-what.html
            '';
          };
        };

      mediaDir = mkOption {
        type = with types; nullOr str;
        default = null;
        example = "/data/media";
        apply =
          path:
          if (path != null) then
            assert assertMsg (path != "" && path != "/") "Media dir must not be empty or root";
            assert assertMsg (head (stringToCharacters path) == "/") "Media dir must be an absolute path";
            lib.${ns}.impermanencePrefix config path
          else
            null;
        description = ''
          Absolute path to directory where media will be stored on this host.
          The directory along with movies, shows, books and music
          subdirectories are automatically created if the value is not null.
        '';
      };
    };

    asserts = [
      (cfg.type != null)
      "Filesystem type must be set"
    ];

    zramSwap.enable = cfg.swap.compression == "zram";

    swapDevices = mkIf cfg.swap.file.enable (singleton {
      device = lib.${ns}.impermanencePrefix config "/swapfile";
      size = cfg.swap.file.size;
    });

    boot = {
      zswap.enable = cfg.swap.compression == "zswap";
      initrd.systemd.enable = true;
      tmp.useTmpfs = cfg.tmpfsTmp;

      loader = mkIf (!raspberry-pi.enable) {
        efi.canTouchEfiVariables = true;
        timeout = mkIf cfg.extendedLoaderTimeout 30;
        systemd-boot = {
          enable = true;
          editor = false;
          consoleMode = "auto";
          configurationLimit = 10;
        };
      };
    };

    programs.zsh.shellAliases."boot-bios" = "systemctl reboot --firmware-setup";

    systemd.tmpfiles.rules = mkIf (cfg.mediaDir != null) (mkBefore [
      "d ${cfg.mediaDir} 0770 root media - -"
      "d ${cfg.mediaDir}/movies 0775 root media - -"
      "d ${cfg.mediaDir}/shows 0775 root media - -"
      "d ${cfg.mediaDir}/books 0775 root media - -"
      "d ${cfg.mediaDir}/music 0775 root media - -"
    ]);

    users = mkIf (cfg.mediaDir != null) {
      users.${username}.extraGroups = [ "media" ];
      groups.media = { };
    };

    # Rather than syncing to disk every 5 secs sync every 15 secs. Marginal
    # efficiency improvement for laptops where sudden powerloss risk is low.
    boot.kernel.sysctl."vm.dirty_writeback_centisecs" = mkIf (device.type == "laptop") 1500;
  }

  (mkIf (cfg.type == "ext4") {
    services.fstrim.enable = cfg.ext4.trim;
  })

  (mkIf (cfg.type == "zfs") {
    # We use legacy ZFS mountpoints and use systemd to mount them rather than
    # ZFS' auto-mount. Might want to switch to using the ZFS native mountpoints
    # and mounting with the zfs-mount-generator in the future.
    # https://github.com/NixOS/nixpkgs/issues/62644
    systemd.services.zfs-mount.enable = false;

    services.zfs = {
      trim.enable = cfg.zfs.trim;
      autoScrub.enable = true;
    };

    boot = {
      # ZFS does not always support the latest kernel so safest option is to
      # default to LTS kernel on all hosts. If a host needs the latest kernel
      # for hardware support it should be overriden in their hardware
      # configuration.
      kernelPackages = pkgs.linuxPackages;
      zfs.package = pkgs.zfs;
      # ZFS will refuse to import pools that were last imported on other hosts
      # (unless the previous host explicitly exported the pool OR this option
      # is enabled - meaning `import` is passed the -f flag). This is relevant
      # when switching between physical hosts or booting different installs
      # e.g. booting an ISO. It should be safe for us to NOT force import as
      # import should never fail as long as hostid is stable. However, I don't
      # want to risk this on headless hosts which would be a massive pain to
      # recover therefore I will continue to force import on those where it
      # realistically has very little risk. Just need to remember to `zpool
      # export` in sitations such as after importing a pool in an ISO for
      # recovery or before moving a pool to another host.
      zfs.forceImportRoot = device.type == "server";

      supportedFilesystems.zfs = true;

      # Set zfs devNodes to "/dev/disk/by-path" for VM installs to fix zpool
      # import failure. Make sure the disks in disko have VM install overrides
      # configured.
      # https://discourse.nixos.org/t/cannot-import-zfs-pool-at-boot/4805
      zfs.devNodes = mkIf inputs.vmInstall.value (mkVMOverride "/dev/disk/by-path");

      # Modify the ZFS import service to allow passwordless native ZFS
      # encryption unlocking using a passphrase decrypted with TPM 2.0
      initrd.systemd =
        let
          nixosUtils = import "${inputs.nixpkgs}/nixos/lib/utils.nix" { inherit lib pkgs config; };
          zfsFilesystems = filter (x: x.fsType == "zfs") config.system.build.fileSystems;
          datasetToPool = x: elemAt (splitString "/" x) 0;
          fsToPool = fs: datasetToPool fs.device;
          rootPools = unique (map fsToPool (filter nixosUtils.fsNeededForBoot zfsFilesystems));
        in
        mkIf (cfg.zfs.encryption.enable && cfg.zfs.encryption.passphraseCred != null) {
          # We have to add our custom script to storePaths so that it's available
          # in initrd. This isn't needed when using the "script" systemd
          # attribute as it makes a job script that gets automatically added to
          # storePaths.
          storePaths = map (
            pool: config.boot.initrd.systemd.services."zfs-import-${pool}".serviceConfig.ExecStart
          ) rootPools;

          services = listToAttrs (
            map (
              pool:
              let
                systemd = config.boot.initrd.systemd.package;
                systemd-creds = getExe' systemd "systemd-creds";
                zfs = "${config.boot.zfs.package}/sbin/zfs";

                # This isn't nice but it's the best way I can think of achieving this
                # without redefining the entire ZFS module or maintaining a nixpkgs
                # fork. Hopefully something like https://github.com/NixOS/nixpkgs/pull/251715
                # gets merged eventually. The upstream systemd service defines
                # the script using `systemd.service.<name>.script`. To avoid
                # infinite recursion we override ExecStart with a new script
                # containing a modified version of the original script.

                # Generate with passphrase creds with:
                # systemd-ask-password -n | systemd-creds encrypt --with-key=tpm2 --name=zfs-passphrase - -
                # PCR 11 doesn't seem to work unfortunately
                customImportScript = getExe (
                  pkgs.writeShellScriptBin "zfs-import-${pool}-custom" (
                    replaceStrings
                      [ "prompt )\n      tries=3\n      success=false\n" ]
                      [
                        # bash
                        ''
                          # indent anchor
                              prompt )
                                # Attempt to load the passphrase from systemd-creds then fallback to manual
                                # passphrase entry

                                if [ ! -v tpm_passphrase ]; then
                                  # We need to decrypt here instead of using SetCredentialEncrypted so that
                                  # import will still work if decryption fails. For some reason if
                                  # SetCredentialEncrypted creds fail to decrypt, the entire service fails.

                                  # Store the passphrase in a variable so that the same passphrase can be used to
                                  # decrypt multiple datasets. Obviously this makes the assumption that all our
                                  # datasets are encrypted with the same passphrase.
                                  ${
                                    if hostname == "homelab" then
                                      ''
                                        tpm_passphrase="${cfg.zfs.encryption.passphraseCred}"
                                      ''
                                    else
                                      ''
                                        tpm_passphrase="$(${systemd-creds} decrypt --name= - - <<< "${cfg.zfs.encryption.passphraseCred}" || true)"
                                      ''
                                  }
                                fi

                                echo "$tpm_passphrase" | ${zfs} load-key "$ds" \
                                  && success=true || success=false
                                tries=10
                        ''
                      ]
                      # Prepend the script with "set -e" to emulate upstream's `makeJobScript`
                      ("set -e\n" + config.boot.initrd.systemd.services."zfs-import-${pool}".script)
                  )
                );
              in
              nameValuePair "zfs-import-${pool}" {
                after = [ "tpm2.target" ];
                serviceConfig.ExecStart = mkForce customImportScript;
              }
            ) rootPools
          );
        };
    };
  })

  (mkIf cfg.zramFs.enable {
    boot =
      let
        # The zramSwap NixOS module reserves devices 0 to swapDevices-1
        device = if config.zramSwap.enable then config.zramSwap.swapDevices else 0;
      in
      {
        kernelParams = [ "zram.num_devices=${toString (device + 1)}" ];
        initrd.kernelModules = [ "zram" ];

        initrd.systemd.services."zram-rootfs" = {
          wantedBy = [ "initrd.target" ];
          requiredBy = [ "sysroot.mount" ];
          before = [ "sysroot.mount" ];
          # we need the zram module to load first so depend on systemd-modules-load
          requires = [ "systemd-modules-load.service" ];
          after = [ "systemd-modules-load.service" ];
          unitConfig.DefaultDependencies = false;
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
          };
          path = with pkgs; [
            e2fsprogs
            util-linux
          ];
          script = ''
            # The device has to be /dev/zram1 because this zramSwap nixos module is
            # hardcoded to /dev/zram0. This is also probably necessary to reliably
            # set mem_limit.
            zramctl /dev/zram${toString device} --size ${cfg.zramFs.size} --algorithm ${cfg.zramFs.algorithm}
            echo ${cfg.zramFs.memoryLimit} > /sys/block/zram${toString device}/mem_limit
            # -m 0: no need to reserve space for superuser
            # -O ...: optimise for RAM-based ephemeral use
            # -E nodiscard: not formatting an actual SSD
            mkfs.ext4 \
              -m 0 \
              -O "^has_journal,^huge_file,^flex_bg,^metadata_csum,^resize_inode" \
              -E nodiscard,lazy_itable_init=0 \
              /dev/zram${toString device}
          '';
        };
      };
  })
]
